export const storeProducts = [
  {
    id: 1,
    title: "Calicut Roofing Tile\n(Single Groove)",
    item: "Roofing Tile",
    img: "img/product-1.png",
    price: 0,
    company: "Calicut Tile Company",
    info:
      "Roofing Tile (Single Groove) \n 420 x 250 (mm) \n 16.5 x 9.8 (Inch)\n 1313 (100 Sq. M)\n 122 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Calicut Roofing Tile\n (Double Groove)",
    item: "Roofing Tile",
    img: "img/product-2.png",
    price: 0,
    company: "Calicut Tile Company",
    info:
      "Roofing Tile (Double Groove)\n420 x 250 (mm) \n 16.5 x 9.8 (Inch)\n1313 (100 Sq. M)\n122 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Calicut Roofing Tile\n (Glass Tile)",
    item: "Glass Tile",
    img: "img/product-3.png",
    price: 0,
    company: "Calicut Tile Company",
    info:
      "Skylight (Glass Tile)\n420 x 250 (mm) \n16.5 x 9.8 (Inch)\n1313 (100 Sq. M)\n122 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Calicut Roofing Tile\n (Ridge Tile)",
    item: "Ridge Tile",
    img: "img/product-4.png",
    price: 0,
    company: "Calicut Tile Company",
    info:
      "Ridge Tile\n430 x 270 (mm) \n19.6 x 10.6 (Inch)\n262 (100 Sq. M)\n80 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Calicut Roofing Tile\n (Decorative Ridge)",
    item: "Ridge Tile",
    img: "img/product-5.png",
    price: 0,
    company: "Calicut Tile Company",
    info:
      "Decorative Ridge\n430 x 270 (mm) \n19.6 x 10.6 (Inch)\n262 (100 Sq. M)\n80 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Calicut Roofing Tile\n (Taylor Tile)",
    item: "Ceiling Tile",
    img: "img/product-6.png",
    price: 0,
    company: "Calicut Tile Company",
    info:
      "Ceiling Tile\n320x210x15(mm) \n12.6x8.2x0.6 (Inch)\n1313 (100 Sq. M)\n122 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Calicut Roofing Tile\n (Ceiling Tile)",
    item: "Ceiling Tile",
    img: "img/product-7.png",
    price: 30,
    company: "Calicut Tile Company",
    info:
      "Taylor Tile\n342x241(mm) \n13.4x9.5 (Inch)\n2324 (100 Sq. M)\n2324 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Calicut Ventilator Tile\n (Single)",
    item: "Ventilator Tile",
    img: "img/product-8.png",
    price: 0,
    company: "Calicut Tile Company",
    info: "Ventilator Tile (Single)\n420x250(mm) \n16.5x9.8 (Inch)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Calicut Roofing Tile\n (Double)",
    item: "Ventilator Tile",
    img: "img/product-9.png",
    price: 0,
    company: "Calicut Tile Company",
    info: "Ventilator Tile (Double)\n420x485(mm) \n16.5x19 (Inch)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Calicut Roofing Tile\n (Ceiling Tile)",
    item: "Ceiling Tile",
    img: "img/product-10.png",
    price: 0,
    company: "Calicut Tile Company",
    info: "Valley Tile\n533x343(mm) \n21x13.5 (Inch)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Calicut Roofing Tile\n (Dome - A",
    item: "Dome",
    img: "img/product-11.png",
    price: 0,
    company: "Calicut Tile Company",
    info: "Dome (A)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "Calicut Roofing Tile\n (Dome - B)",
    item: "Dome",
    img: "img/product-12.png",
    price: 0,
    company: "Calicut Tile Company",
    info: "Dome (B)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    title: "Commonwealth Roofing Tile",
    item: "Roofing Tile",
    img: "img/product-13.png",
    price: 0,
    company: "Commonwealth",
    info:
      "Essentially meant for buildings requiring the highest quality of roofing, these double interlocking rooging tiles can withstand every test of strength, reliability and weather worthiness. The possibility of leakage has been completely eliminated and these have been acknowledge as the best tiles existing today. They have low water absorption - a mere 17%, a breaking strength of 128kg in a wet state and dimensions of417mm * 261mm.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title: "Commonwealth Ridge Tiles",
    item: "Ridge Tile",
    img: "img/product-14.png",
    price: 0,
    company: "Commonwealth",
    info:
      "Measuring 16 long, each Ridge Tile covers 2 flat tiles on each side of the ridge. Weighing roughly 3.4kg. each, our Ridges Tiles, turned out by machinery, achive hihg levels of strength, finish, overlap and catch-groove. 280 tiles are required for 100 running meters. 1000 ridge tiles occupy a Bulk Volume of 4.5 cubic metres.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    title: "Commonwealth Ceiling Tiles",
    item: "Ceiling Tile",
    img: "img/product-15.png",
    price: 0,
    company: "Commonwealth",
    info:
      "Along with Mangalore tiles over them, Ceiling tiles from cheap, effective and simple double roofing system with air space between them. These tiles cover the same area as the roofing tiles and go a long way in creating a pleasant temperature in the room.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 16,
    title: "ELABANO",
    item: "Ceramic Roofing Tile",
    img: "img/ELABANO-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 305mm x 480mm\nWeight: 4.6kg/piece\nPieces for every square: 9.8 pieces",
    inCart: false,
    color: [
      "Coffee Brown | ",
      "Grey Blue | ",
      "Semi Glossy Grey | ",
      "Dark Grey | ",
      "Teracotta Red | ",
      "Mat Grey | ",
      "Rossy Red | ",
      "Shadow Red | ",
      "Bottem Red | ",
      "Antique Red | ",
    ],
    i: 0,
    colorcount: 10,
    colortemp: 1,
    type: "EAST ASIAN SERIES",
    color1: "Coffee Brown",
    count: 0,
    total: 0,
  },
  {
    id: 17,
    title: "NATURA-PLANUM",
    item: "Ceramic Roofing Tile",
    img: "img/NATURA-PLANUM-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 305mm x 480mm\nWeight: 4.6kg/piece\nPieces for every square: 9.8 pieces",
    inCart: false,
    color: [
      "Dark Grey | ",
      "Coffee Brown | ",
      "Teracotta | ",
      "Antique Schatten | ",
      "Antique Schatten Brown | ",
    ],
    i: 0,
    colorcount: 5,
    colortemp: 1,
    type: "GERMAN SERIES",
    color1: "Dark Grey",
    count: 0,
    total: 0,
  },
  {
    id: 18,
    title: "PIANO-CURVE",
    item: "Ceramic Roofing Tile",
    img: "img/PIANO-CURVE-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: ["Coffee Brown | ", "Saffron Red | ", "Semi Grey | "],
    i: 0,
    colorcount: 3,
    colortemp: 1,
    type: "GERMAN SERIES",
    color1: "Coffee Brown",
    count: 0,
    total: 0,
  },
  {
    id: 19,
    title: "PIANO-EDGE",
    item: "Ceramic Roofing Tile",
    img: "img/PIANO-EDGE-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: ["Coffee Brown | ", "Saffron Red | ", "Matte Black | "],
    i: 0,
    colorcount: 3,
    colortemp: 1,
    type: "GERMAN SERIES",
    color1: "Coffee Brown",
    count: 0,
    total: 0,
  },
  {
    id: 20,
    title: "PIANO-FLAT",
    item: "Ceramic Roofing Tile",
    img: "img/PIANO-FLAT-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 300mm x 400mm\nWeight: 2.8kg/piece\nThickness: 13mm\nPieces for every square: 10 pieces",
    inCart: false,
    color: ["Dark Grey | ", "Grey Blue | ", "Antique Red | ", "Grey | "],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "GERMAN SERIES",
    color1: "Dark Grey",
    count: 0,
    total: 0,
  },
  {
    id: 21,
    title: "J-TYPE",
    item: "Ceramic Roofing Tile",
    img: "img/J-TYPE-1.jpg",
    price: 0,
    company: "Lamit",
    info: "Size: 305mm x 305mm\nPieces for every square: 15 pieces",
    inCart: false,
    color: [
      "Antique Red | ",
      "Teracotta Red | ",
      "Dark Grey | ",
      "Coffee Brown | ",
      "Grey Blue | ",
    ],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "JAPANESE SERIES",
    color1: "Antique Red",
    count: 0,
    total: 0,
  },
  {
    id: 22,
    title: "ROMANO-NATURA",
    item: "Ceramic Roofing Tile",
    img: "img/ROMANO-NATURA-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 315mm x 485mm\nWeight: 4.6kg/piece\nPieces for every square: 9.3 pieces",
    inCart: false,
    color: [
      "LM10104-R1 | ",
      "LM10201-R1 | ",
      "LM1055-2-R1 | ",
      "LM1055-R1 | ",
      "LM1085-R1 | ",
      "LM1080-2-R1 | ",
      "LM1082-R1 | ",
      "LM1085-4-R1 | ",
      "LM1006-R1 | ",
      "LM1051-1-R1 | ",
      "LM1063-R1 | ",
      "LM1057-R1 | ",
      "LM1022-3-R1 | ",
      "LM1042-R1 | ",
      "LM1062-R1 | ",
    ],
    i: 0,
    colorcount: 15,
    colortemp: 1,
    type: "ROMAN SERIES",
    color1: "LM10104-R1",
    count: 0,
    total: 0,
  },
  {
    id: 23,
    title: "NATURA-NOVO-COPPO",
    item: "Ceramic Roofing Tile",
    img: "img/NATURA-NOVO-COPPO-1.jpg",
    price: 0,
    company: "Lamit",
    info: "Size: 300mm x 400mm\nPieces for every square: 10 pieces",
    inCart: false,
    color: [
      "Antichizzato Classico | ",
      "Antic Piemonte | ",
      "Giallo | ",
      "Rossa Natura | ",
      "Vecchia Urbino | ",
    ],
    i: 0,
    colorcount: 5,
    colortemp: 1,
    type: "ROMAN SERIES",
    color1: "Antichizzato Classico",
    count: 0,
    total: 0,
  },
  {
    id: 24,
    title: "TEGOLE-NATURA",
    item: "Ceramic Roofing Tile",
    img: "img/TEGOLE-NATURA-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 300mm x 400mm\nWeight: 3.6kg/piece\nPieces for every square: 10 pieces",
    inCart: false,
    color: [
      "Rossa Natura | ",
      "New Romano | ",
      "Testa Di Moro | ",
      "Vecchia Urbino | ",
      "Antica Montefeltro | ",
      "Antica Cipro | ",
    ],
    i: 0,
    colorcount: 6,
    colortemp: 1,
    type: "ROMAN SERIES",
    color1: "Rossa Natura",
    count: 0,
    total: 0,
  },
  {
    id: 25,
    title: "TERRASA",
    item: "Ceramic Roofing Tile",
    img: "img/TERRASA-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 265mm x 400mm\nWeight: 2.9kg/piece\nThickness: 14mm\nPieces for every square: 12 pieces",
    inCart: false,
    color: [
      "Antique Red | ",
      "Dark Grey | ",
      "Coffee Brown | ",
      "Teracotta Red | ",
      "Grey Blue | ",
    ],
    i: 0,
    colorcount: 5,
    colortemp: 1,
    type: "ROMAN SERIES",
    color1: "Antique Red",
    count: 0,
    total: 0,
  },
  {
    id: 26,
    title: "PORTO",
    item: "Ceramic Roofing Tile",
    img: "img/PORTO-1.jpg",
    price: 0,
    company: "Lamit",
    info: "Size: 300mm x 400mm\nPieces for every square: 10 pieces",
    inCart: false,
    color: [
      "Antique Red | ",
      "Matte Black | ",
      "Teracotta Natural Red |",
      "Grey Blue | ",
    ],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "ROMAN SERIES",
    color1: "Antique Red",
    count: 0,
    total: 0,
  },
  {
    id: 27,
    title: "VALANCIA",
    item: "Ceramic Roofing Tile",
    img: "img/VALANCIA-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 310mm x 310mm\nWeight: 1.6kg/piece\nThickness: XXmm\nPieces for every square: 14 pieces",
    inCart: false,
    color: [
      "Antique Red | ",
      "Dark Grey | ",
      "Deep Coffee Brown | ",
      "Grey Blue | ",
    ],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "SPANISH SERIES",
    color1: "Antique Red",
    count: 0,
    total: 0,
  },
  {
    id: 28,
    title: "MINI-VALANCIA",
    item: "Ceramic Roofing Tile",
    img: "img/MINI-VALANCIA-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 260mm x 260mm\nWeight: 1.6kg/piece\nThickness: XXmm\nPieces for every square: 17 pieces",
    inCart: false,
    color: [
      "Antique Red | ",
      "Dark Grey | ",
      "Deep Coffee Brown | ",
      "Grey Blue | ",
    ],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "SPANISH SERIES",
    color1: "Antique Red",
    count: 0,
    total: 0,
  },
  {
    id: 29,
    title: "NATURA-BARREL",
    item: "Ceramic Roofing Tile",
    img: "img/NATURA-BARREL-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: [
      "LM1051-1 | ",
      "LM1051-2 | ",
      "LM1051-3 | ",
      "LM1055 | ",
      "LM1085-T1 | ",
      "LM1056-2-T2 | ",
      "LM1080-2-T1 | ",
      "LM1082-T1 | ",
      "LM1084-T1 | ",
      "LM10107 | ",
      "LM10201 | ",
      "LM1022-3 | ",
      "LM1022-4 | ",
      "LM10101 | ",
    ],
    i: 0,
    colorcount: 14,
    colortemp: 1,
    type: "SPANISH SERIES",
    color1: "LM1051-1",
    count: 0,
    total: 0,
  },
  {
    id: 30,
    title: "MARSEILLE",
    item: "Ceramic Roofing Tile",
    img: "img/MARSEILLE-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: [
      "Matte Black | ",
      "Coffee Brown | ",
      "Saffron Red | ",
      "Grey Blue | ",
    ],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "FRENCH SERIES",
    color1: "Matte Black",
    count: 0,
    total: 0,
  },
  {
    id: 31,
    title: "PIANO-RIBS",
    item: "Ceramic Roofing Tile",
    img: "img/PIANO-RIBS-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: ["Matte Black | ", "Saffron Red | ", "Semi Grey | ", "Grey Blue | "],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "FRENCH SERIES",
    color1: "Matte Black",
    count: 0,
    total: 0,
  },
  {
    id: 33,
    title: "RHINE-FLOW",
    item: "Ceramic Roofing Tile",
    img: "img/RHINE-FLOW-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: ["Matte Black | ", "Saffron Red | ", "Grey Blue | "],
    i: 0,
    colorcount: 3,
    colortemp: 1,
    type: "FRENCH SERIES",
    color1: "Matte Black",
    count: 0,
    total: 0,
  },
  {
    id: 34,
    title: "Wienerberger 400x200x200",
    item: "Hollow Clay Block",
    img: "img/hollow-clay-block.jpg",
    price: 0,
    company: "Wienerberger",
    info:
      "Size: 400mm x 200m x 200mm(Length x Width x Heigth)\nSize: 16 x 8 x 8 (inch)\nWeight: 11.1kg/piece\nDensity:694 kg/m3\nFire Insulation: 240 min",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 35,
    title: "Wienerberger 400x150x200",
    item: "Hollow Clay Block",
    img: "img/Hollow-Clay-Bricks.jpg",
    price: 0,
    company: "Wienerberger",
    info:
      "Size: 400mm x 150m x 200mm(Length x Width x Heigth)\nSize: 16 x 6 x 8 (inch)\nWeight: 8.8kg/piece\nDensity:733 kg/m3\nFire Insulation: 120 min",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 36,
    title: "Wienerberger 400x100x200",
    item: "Hollow Clay Block",
    img: "img/hollow-clay-block3.jpg",
    price: 42,
    company: "Wienerberger",
    info:
      "Size: 400mm x 100m x 200mm(Length x Width x Heigth)\nSize: 16 x 4 x 8 (inch)\nWeight: 6.3kg/piece\nDensity:768 kg/m3\nFire Insulation: 90 min",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 37,
    title: "Piccado-Ceramic",
    item: "Ceramic Roofing Tile",
    img: "img/Piccado-Ceramic-1.jpg",
    price: 0,
    company: "Piccado",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: ["Double Shade | ", "Ink Blue | ", "Blue Grey | ", "Coffe Brown |"],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "Ceramic",
    color1: "Double Shade",
    count: 0,
    total: 0,
  },
  {
    id: 38,
    title: "Piccado-Clay",
    item: "Ceramic Roofing Tile",
    img: "img/Piccado-Clay-1.jpg",
    price: 0,
    company: "Piccado",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: ["Iron Red Tile | ", "Coffe Brown Tile | ", "Matt Black Tile |"],
    i: 0,
    colorcount: 3,
    colortemp: 1,
    type: "Clay",
    color1: "Iron Red Tile",
    count: 0,
    total: 0,
  },
  {
    id: 39,
    title: "MaxLite AAC Block 4inch",
    item: "AAC Blocks",
    img: "img/maxlite1.jpg",
    price: 0,
    company: "Maxlite AAC Blocks",
    info:
      "Size: 600mm x 200mm x 100mm\nShape: Rectangular\nMaterial: Autoclaved Aerated Concrete\nWe are the most premium MaxliteAAC blocks manufacturers in south india. With our products make your construction more stronger.Maxlite Light Weight Aac Block",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 40,
    title: "MaxLite AAC Block 6inch",
    item: "AAC Blocks",
    img: "img/maxlite2.jpg",
    price: 0,
    company: "Maxlite AAC Blocks",
    info:
      "Size: 600mm x 200mm x 150mm\nShape: Rectangular\nMaterial: Autoclaved Aerated Concrete\nWe are the most premium MaxliteAAC blocks manufacturers in south india. With our products make your construction more stronger.Maxlite Light Weight Aac Block",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 41,
    title: "MaxLite AAC Block 8inch",
    item: "AAC Blocks",
    img: "img/maxlite3.jpg",
    price: 0,
    company: "Maxlite AAC Blocks",
    info:
      "Size: 600mm x 200mm x 200mm\nShape: Rectangular\nMaterial: Autoclaved Aerated Concrete\nWe are the most premium MaxliteAAC blocks manufacturers in south india. With our products make your construction more stronger.Maxlite Light Weight Aac Block",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 42,
    title: "Renacon AAC Block 4inch",
    item: "AAC Blocks",
    img: "img/renacon1.jpg",
    price: 0,
    company: "Renacon AAC Blocks",
    info:
      "Size: 600mm * 200mm * 100 mm\nShape: Rectangular\nWeigth: 9 kg\nMaterial: Autoclaved Aerated Concrete\nWe are the most premium RenaconAAC blocks manufacturers in south india. With our products make your construction more stronger.Renacon Light Weight Aac Block",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 43,
    title: "Renacon AAC Block 6inch",
    item: "AAC Blocks",
    img: "img/renacon2.jpg",
    price: 0,
    company: "Renacon AAC Blocks",
    info:
      "Size: 600mm * 200mm * 150 mm\nShape: Rectangular\nWeigth: 13 kg\nMaterial: Autoclaved Aerated Concrete\nWe are the most premium ReanaconAAC blocks manufacturers in south india. With our products make your construction more stronger.Renacon Light Weight Aac Block",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 44,
    title: "Renacon AAC Block 8inch",
    item: "AAC Blocks",
    img: "img/renacon3.jpg",
    price: 0,
    company: "Renacon AAC Blocks",
    info:
      "Size: 600mm * 200mm * 200 mm\nShape: Rectangular\nWeigth: 18 kg\nMaterial: Autoclaved Aerated Concrete\nWe are the most premium RenaconAAC blocks manufacturers in south india. With our products make your construction more stronger.Renacon Light Weight Aac Block",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 45,
    title: "Star Clay Tiles",
    item: "AAC Blocks",
    img: "img/starclay11.png",
    price: 0,
    company: "Star Clay Tiles",
    info:
      "Size: 600mm * 200mm * 200 mm\nShape: Rectangular\nWeigth: 18 kg\nMaterial: Autoclaved Aerated Concrete\nWe are the most premium RenaconAAC blocks manufacturers in south india. With our products make your construction more stronger.Renacon Light Weight Aac Block",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 46,
    title: "DOUBLE GADI ROOFING TILE(Thomson)",
    item: "Roofing Tile",
    img: "img/thomson1.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DG1001\nSize: 16.5 x 10. 25(inch)\nNos./100Sqt: 115\nWt/Pc: 2.900Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 47,
    title: "SINGLE GADI ROOFING TILE(Thomson)",
    item: "Roofing Tile",
    img: "img/thomson2.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: SG1002\nSize:  16 x 9.5(inch)\nNos./100Sqt: 130\nWt/Pc: 2.250Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 48,
    title: "RIDGE TILE(Thomson)",
    item: "Ridge Tile",
    img: "img/thomson3.png",
    price: 0,
    company: "Thomson Tiles",
    info: "Code: RD1004\nSize:  16 x 10(inch)\nNos./100Sqt: 80\nWt/Pc: 3.800Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 49,
    title: "CEILING TILE (Thomson)",
    item: "Ceiling Tile",
    img: "img/thomson4.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: CT1003\nSize:  12.5 x 8.5(inch)\nNos./100Sqt: 158\nWt/Pc: 2.000Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 50,
    title: "SMOKE TILE (Thomson)",
    item: "Ventilator Tile",
    img: "img/thomson5.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: ST 1005\nSize:  16 x 9.5(inch)\nNos./100Sqt: 130\nWt/Pc: 2.900Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 51,
    title: "VALLEY TILE(Thomson)",
    item: "Valley Tile",
    img: "img/thomson6.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: VT 1006\nSize:  16.5 x 10(inch)\nNos./100Sqt: 80\nWt/Pc: 3.000Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 52,
    title: "KOOMBU(Thomson)",
    item: "Valley Tile",
    img: "img/thomson7.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: KM2002  - Size: 19 (inch)\nCode KM2003  - Size: 16 (inch)\nCode KM2005  - Size: 13 (inch)\nCode KM2006  - Size: 11 (inch)\nCode KM2004  - Size: 19 (inch)\nCode KM2001  - Size: 22 (inch)\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 53,
    title: "JOLLY BRICKS(Thomson)",
    item: "Jolly Bricks",
    img: "img/thomson8.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: JB 5001\nSize:  8 x 8 x 3(inch)\nNos./100Sqt: 225\nWt/Pc: 2.500Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 54,
    title: "JOLLY BRICKS(Thomson)",
    item: "Jolly Bricks",
    img: "img/thomson9.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: JB 5008\nSize:  7.5 x 7.5 x 3(inch)\nNos./100Sqt: 226\nWt/Pc: 2.250Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 55,
    title: "PERFORATED BRICKS(Thomson)",
    item: "Perforated Bricks",
    img: "img/thomson10.png",
    price: 0,
    company: "Thomson Tiles",
    info: "Code: PB4007\nSize:  9 x 4.25 x 3(inch)\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 56,
    title: "PERFORATED BRICKS(Thomson)",
    item: "Perforated Bricks",
    img: "img/thomson11.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: PBR4009\nSize: 9 x 4.25 x 3(inch)\nNos./100Sqt: 535\nWt/Pc: 2.900Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 57,
    title: "PERFORATED BRICKS(Thomson)",
    item: "Perforated Bricks",
    img: "img/thomson12.png",
    price: 0,
    company: "Thomson Tiles",
    info: "Code: PB4008\nSize: 8 x 5.75 x 3(inch)\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 58,
    title: "HOLLOW BRICKS(Thomson)",
    item: "Hollow Clay Block",
    img: "img/thomson13.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: ------HB4004  --- HB4005\nSize(inch): 12x4x3  ---- 9x4x3\nNos./100Sqt: 400  ------ 535\nWt/Pc: ----2.700Kg  ---- 2.300Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 59,
    title: "HOLLOW BRICK(Thomson)",
    item: "Hollow Clay Block",
    img: "img/thomson14.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: HB 4006\nSize: 12 x 6 x 2(inch)\nNos./100Sqt: 200\nWt/Pc: 3.000Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 60,
    title: "HOLLOW BRICKS(Thomson)",
    item: "Hollow Clay Block",
    img: "img/thomson15.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: HB4012 - Size(inch): 14x8x6 -Nos./100Sqt: 171 - Wt/Pc: 10Kg\nCode: HB4013 - Size(inch): 12x8x6 -Nos./100Sqt: 200 - Wt/Pc: 8.1Kg\nCode: HB4001 - Size(inch): 14x7x6 -Nos./100Sqt: 171 - Wt/Pc: 8.250Kg\nCode: HB4002 - Size(inch): 12x6x6 -Nos./100Sqt: 200 - Wt/Pc: 6.200Kg\nCode: HB4003 - Size(inch): 12x6x4 -Nos./100Sqt: 300 - Wt/Pc: 4.000Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 61,
    title: "DOUBLE GUADI ROOFING TILE(Thomson)",
    item: "Roofing Tile",
    img: "img/thomson16.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DD45001\nSize: 16.5 x 10.25(inch)\nNos./100Sqt: 115\nWt/Pc:2.600Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 62,
    title: "DG ROOF TILE(Thomson)",
    item: "Roofing Tile",
    img: "img/thomson17.png",
    price: 0,
    company: "Thomson Tiles",
    info: "Code: DDG6000\nSize: 14 x 9(inch)\nNos./100Sqt: 150\nWt/Pc:2.100Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 63,
    title: "FLOORING TILE (SQUARE)(Thomson)",
    item: "Flooring Tile",
    img: "img/thomson18.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: FT7001 - Size(inch): 9x9 -Nos./100Sqt: 178 - Wt/Pc: 1.300Kg\nCode: FT7002 - Size(inch): 8x8 -Nos./100Sqt: 225 - Wt/Pc: 1.150Kg\nCode: FT7003 - Size(inch): 7x7 -Nos./100Sqt: 294 - Wt/Pc: 0.950Kg\nCode: FT7004 - Size(inch): 6x6 -Nos./100Sqt: 400 - Wt/Pc: 0.620Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 64,
    title: "FLOORING TILE (HEXAGON)(Thomson)",
    item: "Flooring Tile",
    img: "img/thomson19.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: FT7005 - Size(inch): 8x8 -Nos./100Sqt: 230 - Wt/Pc: 1.000Kg\nCode: FT7006 - Size(inch): 6x6 -Nos./100Sqt: 410 - Wt/Pc: 0.600Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 65,
    title: "CEILING TILE (FLOWER)(Thomson)",
    item: "Ceiling Tile",
    img: "img/thomson20.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DCL8001 - Size(inch): 12.5x8.5 -Nos./100Sqt: 158 - Wt/Pc: 1.800Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 66,
    title: "CEILING TILE (MAT)(Thomson)",
    item: "Ceiling Tile",
    img: "img/thomson21.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DCL8002 - Size(inch): 12.5x8.5 -Nos./100Sqt: 158 - Wt/Pc: 1.800Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 67,
    title: "CEILING TILE (STRIPE)(Thomson)",
    item: "Ceiling Tile",
    img: "img/thomson22.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DCL8005 - Size(inch): 12.5x8.5 -Nos./100Sqt: 158 - Wt/Pc: 1.800Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 68,
    title: "CEILING TILE (ANTIC)(Thomson)",
    item: "Ceiling Tile",
    img: "img/thomson23.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DCL8006 - Size(inch): 12.5x8.5 -Nos./100Sqt: 158 - Wt/Pc: 1.800Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 69,
    title: "CEILING TILE (HONEY COMB)(Thomson)",
    item: "Ceiling Tile",
    img: "img/thomson24.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DCL8003 - Size(inch): 12.5x8.5 -Nos./100Sqt: 158 - Wt/Pc: 1.800Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 70,
    title: "CEILING TILE (PLAIN)(Thomson)",
    item: "Ceiling Tile",
    img: "img/thomson25.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DCL8004 - Size(inch): 12.5x8.5 -Nos./100Sqt: 158 - Wt/Pc: 1.800Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 71,
    title: "CEILING TILE (WEB)(Thomson)",
    item: "Ceiling Tile",
    img: "img/thomson26.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DCL8007 - Size(inch): 12.5x8.5 -Nos./100Sqt: 158 - Wt/Pc: 1.800Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 72,
    title: "CEILING TILE (KNOT)(Thomson)",
    item: "Ceiling Tile",
    img: "img/thomson27.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DCL8008 - Size(inch): 12.5x8.5 -Nos./100Sqt: 158 - Wt/Pc: 1.800Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 73,
    title: "D.G. ROOF TILE(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson28.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DDG6001 - Size(inch): 12x8 -Nos./100Sqt: 200 - Wt/Pc: 1.600Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 74,
    title: "S.G. ROOF TILE(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson29.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DSG6002 - Size(inch): 11x7 -Nos./100Sqt: 240 - Wt/Pc: 1.100Kg\nCode: DSG6003 - Size(inch): 9x6 -Nos./100Sqt: 360 - Wt/Pc: 0.825Kg\nCode: DSG6004 - Size(inch): 8x5 -Nos./100Sqt: 490 - Wt/Pc: 0.625Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 75,
    title: "SPANISH(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson30.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: D6005 - Size(inch): 8x7 -Nos./100Sqt: 295 - Wt/Pc: 0.900Kg\nCode: D6006 - Size(inch): 7x6 -Nos./100Sqt: 405 - Wt/Pc: 0.650Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 76,
    title: "GOPURAM(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson31.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: D6007 - Size(inch): 8x7 -Nos./100Sqt: 295 - Wt/Pc: 0.900Kg\nCode: D6008 - Size(inch): 7.25x5.50 -Nos./100Sqt: 400 - Wt/Pc: 0.650Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 77,
    title: "ARCHANA(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson32.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: D6007 - Size(inch): 8x7 -Nos./100Sqt: 295 - Wt/Pc: 0.900Kg\nCode: D6008 - Size(inch): 7.25x5.50 -Nos./100Sqt: 400 - Wt/Pc: 0.650Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 78,
    title: "BAMBOO(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson33.png",
    price: 0,
    company: "Thomson Tiles",
    info: "Code: D6011\nSize:  8 x 7(inch)\nNos./100Sqt: 295\nWt/Pc: 0.950Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 79,
    title: "TYLORE(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson34.png",
    price: 0,
    company: "Thomson Tiles",
    info: "Code: D6014\nSize:  9 x 6.5(inch)\nNos./100Sqt: 290\nWt/Pc: 1.000Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 80,
    title: "POLO(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson35.png",
    price: 0,
    company: "Thomson Tiles",
    info: "Code: D6015\nSize:  9 x 6.5(inch)\nNos./100Sqt: 350\nWt/Pc: 1.000Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 81,
    title: "RIDGES(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson36.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: D6016 - Size(inch): 9x6 -Nos./100Sqt: 150 - Wt/Pc: 0.850Kg\nCode: D6017 - Size(inch): 8x5 -Nos./100Sqt: 170 - Wt/Pc: 0.650Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 82,
    title: "DOME TILE(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson37.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: D6020 - Size(inch): 10x4.75 -Nos./100Sqt: 525 - Wt/Pc: 0.750Kg\nCode: D6021 - Size(inch): 8.5x4.75 -Nos./100Sqt: 650 - Wt/Pc: 0.450Kg\n",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 83,
    title: "ROUND RIDGE(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson38.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DD9002\nSize:  11 x 7.25(inch)\nNos./100Sqt: 120\nWt/Pc: 1.300Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 84,
    title: "DUTCH CEILING TILES(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson39.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: D6012\nSize:  8.25 x 6.25(inch)\nNos./100Sqt: 340\nWt/Pc: 1.300Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 85,
    title: "ELBANO(Thomson)",
    item: "Mini Roofing Tiles",
    img: "img/thomson40.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DD9001\nSize:  12 x 10(inch)\nNos./100Sqt: 145\nWt/Pc: 2.000Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 86,
    title: "CLADDING TILE (DIFFERENT COLORS)",
    item: "Cladding Tile",
    img: "img/thomson41.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: DCL10001\nSize:  230x40x18(inch)\nNos./100Sqt: 1000\nWt/Pc: 280g",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 87,
    title: "FACING TILE (DIFFERENT COLORS)",
    item: "Facing Tile",
    img: "img/thomson42.png",
    price: 0,
    company: "Thomson Tiles",
    info: "Code: D6019\nSize:  9x3(inch)\nNos./100Sqt: 533\nWt/Pc: 3.500Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 88,
    title: "THOMSON PATTERN ROOFING (TERACOTTA)",
    item: "Mini Roofing Tiles",
    img: "img/thomson43.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: D9003\nSize:  16.5x10.25(inch)\nNos./100Sqt: 115\nWt/Pc: 2.600Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 89,
    title: "THOMSON PATTERN ROOFING (DOUBLE COLORED)",
    item: "Mini Roofing Tiles",
    img: "img/thomson44.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: D9003A\nSize:  16.5x10.25(inch)\nNos./100Sqt: 115\nWt/Pc: 2.600Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 91,
    title: "PIATTO",
    item: "Mini Roofing Tiles",
    img: "img/thomson45.png",
    price: 0,
    company: "Thomson Tiles",
    info:
      "Code: D9004\nSize:  16.5x10.25(inch)\nNos./100Sqt: 115\nWt/Pc: 2.600Kg",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 92,
    title: "PIATTO CLOURED TILES",
    item: "Mini Roofing Tiles",
    img: "img/thomson46.png",
    price: 0,
    company: "Thomson Tiles",
    info: "information updating soon",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 93,
    title: "THOMSON CLOURED TILES",
    item: "Mini Roofing Tiles",
    img: "img/thomson47.png",
    price: 0,
    company: "Thomson Tiles",
    info: "information updating soon",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 94,
    title: "THOMSON CLOURED TILES",
    item: "Mini Roofing Tiles",
    img: "img/thomson48.png",
    price: 0,
    company: "Thomson Tiles",
    info: "information updating soon",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 95,
    title: "THOMSON CLOURED TILES",
    item: "Mini Roofing Tiles",
    img: "img/thomson49.png",
    price: 0,
    company: "Thomson Tiles",
    info: "information updating soon",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Calicut Roofing Tile\n(Single Groove)",
  item: "Roofing Tile",
  img: "img/product-1.png",
  price: 0,
  company: "Calicut Tile Company",
  info:
    "Roofing Tile (Single Groove) \n 420 x 250 (mm) \n 16.5 x 9.8 (Inch)\n 1313 (100 Sq. M)\n 122 (100 Sq.Ft)",
  inCart: false,
  count: 0,
  total: 0,
};
