export const storeProducts = [
  {
    id: 1,
    title: "Calicut Roofing Tile\n(Single Groove)",
    item: "Roofing Tile",
    img: "img/product-1.png",
    price: 0,
    company: "Calicut Tile Company",
    info:
      "Roofing Tile (Single Groove) \n 420 x 250 (mm) \n 16.5 x 9.8 (Inch)\n 1313 (100 Sq. M)\n 122 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Calicut Roofing Tile\n (Double Groove)",
    item: "Roofing Tile",
    img: "img/product-2.png",
    price: 0,
    company: "Calicut Tile Company",
    info:
      "Roofing Tile (Double Groove)\n420 x 250 (mm) \n 16.5 x 9.8 (Inch)\n1313 (100 Sq. M)\n122 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Calicut Roofing Tile\n (Glass Tile)",
    item: "Glass Tile",
    img: "img/product-3.png",
    price: 0,
    company: "Calicut Tile Company",
    info:
      "Skylight (Glass Tile)\n420 x 250 (mm) \n16.5 x 9.8 (Inch)\n1313 (100 Sq. M)\n122 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Calicut Roofing Tile\n (Ridge Tile)",
    item: "Ridge Tile",
    img: "img/product-4.png",
    price: 0,
    company: "Calicut Tile Company",
    info:
      "Ridge Tile\n430 x 270 (mm) \n19.6 x 10.6 (Inch)\n262 (100 Sq. M)\n80 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Calicut Roofing Tile\n (Decorative Ridge)",
    item: "Ridge Tile",
    img: "img/product-5.png",
    price: 0,
    company: "Calicut Tile Company",
    info:
      "Decorative Ridge\n430 x 270 (mm) \n19.6 x 10.6 (Inch)\n262 (100 Sq. M)\n80 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Calicut Roofing Tile\n (Taylor Tile)",
    item: "Ceiling Tile",
    img: "img/product-6.png",
    price: 0,
    company: "Calicut Tile Company",
    info:
      "Ceiling Tile\n320x210x15(mm) \n12.6x8.2x0.6 (Inch)\n1313 (100 Sq. M)\n122 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Calicut Roofing Tile\n (Ceiling Tile)",
    item: "Ceiling Tile",
    img: "img/product-7.png",
    price: 30,
    company: "Calicut Tile Company",
    info:
      "Taylor Tile\n342x241(mm) \n13.4x9.5 (Inch)\n2324 (100 Sq. M)\n2324 (100 Sq.Ft)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Calicut Ventilator Tile\n (Single)",
    item: "Ventilator Tile",
    img: "img/product-8.png",
    price: 0,
    company: "Calicut Tile Company",
    info: "Ventilator Tile (Single)\n420x250(mm) \n16.5x9.8 (Inch)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Calicut Roofing Tile\n (Double)",
    item: "Ventilator Tile",
    img: "img/product-9.png",
    price: 0,
    company: "Calicut Tile Company",
    info: "Ventilator Tile (Double)\n420x485(mm) \n16.5x19 (Inch)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Calicut Roofing Tile\n (Ceiling Tile)",
    item: "Ceiling Tile",
    img: "img/product-10.png",
    price: 0,
    company: "Calicut Tile Company",
    info: "Valley Tile\n533x343(mm) \n21x13.5 (Inch)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Calicut Roofing Tile\n (Dome - A",
    item: "Dome",
    img: "img/product-11.png",
    price: 0,
    company: "Calicut Tile Company",
    info: "Dome (A)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "Calicut Roofing Tile\n (Dome - B)",
    item: "Dome",
    img: "img/product-12.png",
    price: 0,
    company: "Calicut Tile Company",
    info: "Dome (B)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    title: "Commonwealth Roofing Tile",
    item: "Roofing Tile",
    img: "img/product-13.png",
    price: 0,
    company: "Commonwealth",
    info:
      "Essentially meant for buildings requiring the highest quality of roofing, these double interlocking rooging tiles can withstand every test of strength, reliability and weather worthiness. The possibility of leakage has been completely eliminated and these have been acknowledge as the best tiles existing today. They have low water absorption - a mere 17%, a breaking strength of 128kg in a wet state and dimensions of417mm * 261mm.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title: "Commonwealth Ridge Tiles",
    item: "Ridge Tile",
    img: "img/product-14.png",
    price: 0,
    company: "Commonwealth",
    info:
      "Measuring 16 long, each Ridge Tile covers 2 flat tiles on each side of the ridge. Weighing roughly 3.4kg. each, our Ridges Tiles, turned out by machinery, achive hihg levels of strength, finish, overlap and catch-groove. 280 tiles are required for 100 running meters. 1000 ridge tiles occupy a Bulk Volume of 4.5 cubic metres.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    title: "Commonwealth Ceiling Tiles",
    item: "Ceiling Tile",
    img: "img/product-15.png",
    price: 0,
    company: "Commonwealth",
    info:
      "Along with Mangalore tiles over them, Ceiling tiles from cheap, effective and simple double roofing system with air space between them. These tiles cover the same area as the roofing tiles and go a long way in creating a pleasant temperature in the room.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 16,
    title: "ELABANO",
    item: "Ceramic Roofing Tile",
    img: "img/ELABANO-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 305mm x 480mm\nWeight: 4.6kg/piece\nPieces for every square: 9.8 pieces",
    inCart: false,
    color: [
      "Coffee Brown | ",
      "Grey Blue | ",
      "Semi Glossy Grey | ",
      "Dark Grey | ",
      "Teracotta Red | ",
      "Mat Grey | ",
      "Rossy Red | ",
      "Shadow Red | ",
      "Bottem Red | ",
      "Antique Red | ",
    ],
    i: 0,
    colorcount: 10,
    colortemp: 1,
    type: "EAST ASIAN SERIES",
    color1: "Coffee Brown",
    count: 0,
    total: 0,
  },
  {
    id: 17,
    title: "NATURA-PLANUM",
    item: "Ceramic Roofing Tile",
    img: "img/NATURA-PLANUM-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 305mm x 480mm\nWeight: 4.6kg/piece\nPieces for every square: 9.8 pieces",
    inCart: false,
    color: [
      "Dark Grey | ",
      "Coffee Brown | ",
      "Teracotta | ",
      "Antique Schatten | ",
      "Antique Schatten Brown | ",
    ],
    i: 0,
    colorcount: 5,
    colortemp: 1,
    type: "GERMAN SERIES",
    color1: "Dark Grey",
    count: 0,
    total: 0,
  },
  {
    id: 18,
    title: "PIANO-CURVE",
    item: "Ceramic Roofing Tile",
    img: "img/PIANO-CURVE-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: ["Coffee Brown | ", "Saffron Red | ", "Semi Grey | "],
    i: 0,
    colorcount: 3,
    colortemp: 1,
    type: "GERMAN SERIES",
    color1: "Coffee Brown",
    count: 0,
    total: 0,
  },
  {
    id: 19,
    title: "PIANO-EDGE",
    item: "Ceramic Roofing Tile",
    img: "img/PIANO-EDGE-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: ["Coffee Brown | ", "Saffron Red | ", "Matte Black | "],
    i: 0,
    colorcount: 3,
    colortemp: 1,
    type: "GERMAN SERIES",
    color1: "Coffee Brown",
    count: 0,
    total: 0,
  },
  {
    id: 20,
    title: "PIANO-FLAT",
    item: "Ceramic Roofing Tile",
    img: "img/PIANO-FLAT-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 300mm x 400mm\nWeight: 2.8kg/piece\nThickness: 13mm\nPieces for every square: 10 pieces",
    inCart: false,
    color: ["Dark Grey | ", "Grey Blue | ", "Antique Red | ", "Grey | "],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "GERMAN SERIES",
    color1: "Dark Grey",
    count: 0,
    total: 0,
  },
  {
    id: 21,
    title: "J-TYPE",
    item: "Ceramic Roofing Tile",
    img: "img/J-TYPE-1.jpg",
    price: 0,
    company: "Lamit",
    info: "Size: 305mm x 305mm\nPieces for every square: 15 pieces",
    inCart: false,
    color: [
      "Antique Red | ",
      "Teracotta Red | ",
      "Dark Grey | ",
      "Coffee Brown | ",
      "Grey Blue | ",
    ],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "JAPANESE SERIES",
    color1: "Antique Red",
    count: 0,
    total: 0,
  },
  {
    id: 22,
    title: "ROMANO-NATURA",
    item: "Ceramic Roofing Tile",
    img: "img/ROMANO-NATURA-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 315mm x 485mm\nWeight: 4.6kg/piece\nPieces for every square: 9.3 pieces",
    inCart: false,
    color: [
      "LM10104-R1 | ",
      "LM10201-R1 | ",
      "LM1055-2-R1 | ",
      "LM1055-R1 | ",
      "LM1085-R1 | ",
      "LM1080-2-R1 | ",
      "LM1082-R1 | ",
      "LM1085-4-R1 | ",
      "LM1006-R1 | ",
      "LM1051-1-R1 | ",
      "LM1063-R1 | ",
      "LM1057-R1 | ",
      "LM1022-3-R1 | ",
      "LM1042-R1 | ",
      "LM1062-R1 | ",
    ],
    i: 0,
    colorcount: 15,
    colortemp: 1,
    type: "ROMAN SERIES",
    color1: "LM10104-R1",
    count: 0,
    total: 0,
  },
  {
    id: 23,
    title: "NATURA-NOVO-COPPO",
    item: "Ceramic Roofing Tile",
    img: "img/NATURA-NOVO-COPPO-1.jpg",
    price: 0,
    company: "Lamit",
    info: "Size: 300mm x 400mm\nPieces for every square: 10 pieces",
    inCart: false,
    color: [
      "Antichizzato Classico | ",
      "Antic Piemonte | ",
      "Giallo | ",
      "Rossa Natura | ",
      "Vecchia Urbino | ",
    ],
    i: 0,
    colorcount: 5,
    colortemp: 1,
    type: "ROMAN SERIES",
    color1: "Antichizzato Classico",
    count: 0,
    total: 0,
  },
  {
    id: 24,
    title: "TEGOLE-NATURA",
    item: "Ceramic Roofing Tile",
    img: "img/TEGOLE-NATURA-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 300mm x 400mm\nWeight: 3.6kg/piece\nPieces for every square: 10 pieces",
    inCart: false,
    color: [
      "Rossa Natura | ",
      "New Romano | ",
      "Testa Di Moro | ",
      "Vecchia Urbino | ",
      "Antica Montefeltro | ",
      "Antica Cipro | ",
    ],
    i: 0,
    colorcount: 6,
    colortemp: 1,
    type: "ROMAN SERIES",
    color1: "Rossa Natura",
    count: 0,
    total: 0,
  },
  {
    id: 25,
    title: "TERRASA",
    item: "Ceramic Roofing Tile",
    img: "img/TERRASA-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 265mm x 400mm\nWeight: 2.9kg/piece\nThickness: 14mm\nPieces for every square: 12 pieces",
    inCart: false,
    color: [
      "Antique Red | ",
      "Dark Grey | ",
      "Coffee Brown | ",
      "Teracotta Red | ",
      "Grey Blue | ",
    ],
    i: 0,
    colorcount: 5,
    colortemp: 1,
    type: "ROMAN SERIES",
    color1: "Antique Red",
    count: 0,
    total: 0,
  },
  {
    id: 26,
    title: "PORTO",
    item: "Ceramic Roofing Tile",
    img: "img/PORTO-1.jpg",
    price: 0,
    company: "Lamit",
    info: "Size: 300mm x 400mm\nPieces for every square: 10 pieces",
    inCart: false,
    color: [
      "Antique Red | ",
      "Matte Black | ",
      "Teracotta Natural Red |",
      "Grey Blue | ",
    ],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "ROMAN SERIES",
    color1: "Antique Red",
    count: 0,
    total: 0,
  },
  {
    id: 27,
    title: "VALANCIA",
    item: "Ceramic Roofing Tile",
    img: "img/VALANCIA-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 310mm x 310mm\nWeight: 1.6kg/piece\nThickness: XXmm\nPieces for every square: 14 pieces",
    inCart: false,
    color: [
      "Antique Red | ",
      "Dark Grey | ",
      "Deep Coffee Brown | ",
      "Grey Blue | ",
    ],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "SPANISH SERIES",
    color1: "Antique Red",
    count: 0,
    total: 0,
  },
  {
    id: 28,
    title: "MINI-VALANCIA",
    item: "Ceramic Roofing Tile",
    img: "img/MINI-VALANCIA-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 260mm x 260mm\nWeight: 1.6kg/piece\nThickness: XXmm\nPieces for every square: 17 pieces",
    inCart: false,
    color: [
      "Antique Red | ",
      "Dark Grey | ",
      "Deep Coffee Brown | ",
      "Grey Blue | ",
    ],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "SPANISH SERIES",
    color1: "Antique Red",
    count: 0,
    total: 0,
  },
  {
    id: 29,
    title: "NATURA-BARREL",
    item: "Ceramic Roofing Tile",
    img: "img/NATURA-BARREL-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: [
      "LM1051-1 | ",
      "LM1051-2 | ",
      "LM1051-3 | ",
      "LM1055 | ",
      "LM1085-T1 | ",
      "LM1056-2-T2 | ",
      "LM1080-2-T1 | ",
      "LM1082-T1 | ",
      "LM1084-T1 | ",
      "LM10107 | ",
      "LM10201 | ",
      "LM1022-3 | ",
      "LM1022-4 | ",
      "LM10101 | ",
    ],
    i: 0,
    colorcount: 14,
    colortemp: 1,
    type: "SPANISH SERIES",
    color1: "LM1051-1",
    count: 0,
    total: 0,
  },
  {
    id: 30,
    title: "MARSEILLE",
    item: "Ceramic Roofing Tile",
    img: "img/MARSEILLE-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: [
      "Matte Black | ",
      "Coffee Brown | ",
      "Saffron Red | ",
      "Grey Blue | ",
    ],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "FRENCH SERIES",
    color1: "Matte Black",
    count: 0,
    total: 0,
  },
  {
    id: 31,
    title: "PIANO-RIBS",
    item: "Ceramic Roofing Tile",
    img: "img/PIANO-RIBS-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: ["Matte Black | ", "Saffron Red | ", "Semi Grey | ", "Grey Blue | "],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "FRENCH SERIES",
    color1: "Matte Black",
    count: 0,
    total: 0,
  },
  {
    id: 33,
    title: "RHINE-FLOW",
    item: "Ceramic Roofing Tile",
    img: "img/RHINE-FLOW-1.jpg",
    price: 0,
    company: "Lamit",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: ["Matte Black | ", "Saffron Red | ", "Grey Blue | "],
    i: 0,
    colorcount: 3,
    colortemp: 1,
    type: "FRENCH SERIES",
    color1: "Matte Black",
    count: 0,
    total: 0,
  },
  {
    id: 34,
    title: "Wienerberger 400x200x200",
    item: "Hollow Clay Block",
    img: "img/hollow-clay-block.jpg",
    price: 0,
    company: "Wienerberger",
    info:
      "Size: 400mm x 200m x 200mm(Length x Width x Heigth)\nSize: 16 x 8 x 8 (inch)\nWeight: 11.1kg/piece\nDensity:694 kg/m3\nFire Insulation: 240 min",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 35,
    title: "Wienerberger 400x150x200",
    item: "Hollow Clay Block",
    img: "img/Hollow-Clay-Bricks.jpg",
    price: 0,
    company: "Wienerberger",
    info:
      "Size: 400mm x 150m x 200mm(Length x Width x Heigth)\nSize: 16 x 6 x 8 (inch)\nWeight: 8.8kg/piece\nDensity:733 kg/m3\nFire Insulation: 120 min",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 36,
    title: "Wienerberger 400x100x200",
    item: "Hollow Clay Block",
    img: "img/hollow-clay-block3.jpg",
    price: 42,
    company: "Wienerberger",
    info:
      "Size: 400mm x 100m x 200mm(Length x Width x Heigth)\nSize: 16 x 4 x 8 (inch)\nWeight: 6.3kg/piece\nDensity:768 kg/m3\nFire Insulation: 90 min",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 37,
    title: "Piccado-Ceramic",
    item: "Ceramic Roofing Tile",
    img: "img/Piccado-Ceramic-1.jpg",
    price: 0,
    company: "Piccado",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: ["Double Shade | ", "Ink Blue | ", "Blue Grey | ", "Coffe Brown |"],
    i: 0,
    colorcount: 4,
    colortemp: 1,
    type: "Ceramic",
    color1: "Double Shade",
    count: 0,
    total: 0,
  },
  {
    id: 38,
    title: "Piccado-Clay",
    item: "Ceramic Roofing Tile",
    img: "img/Piccado-Clay-1.jpg",
    price: 0,
    company: "Piccado",
    info:
      "Size: 280mm x 400mm\nWeight: 2.7kg/piece\nThickness: 11mm\nPieces for every square: 11 pieces",
    inCart: false,
    color: ["Iron Red Tile | ", "Coffe Brown Tile | ", "Matt Black Tile |"],
    i: 0,
    colorcount: 3,
    colortemp: 1,
    type: "Clay",
    color1: "Iron Red Tile",
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Calicut Roofing Tile\n(Single Groove)",
  item: "Roofing Tile",
  img: "img/product-1.png",
  price: 0,
  company: "Calicut Tile Company",
  info:
    "Roofing Tile (Single Groove) \n 420 x 250 (mm) \n 16.5 x 9.8 (Inch)\n 1313 (100 Sq. M)\n 122 (100 Sq.Ft)",
  inCart: false,
  count: 0,
  total: 0,
};
